language: node_js

node_js:
  - "6"
  - "7"
  - "8"

env:
  - PACKAGE=idyll-compiler
  - PACKAGE=idyll-components
  - PACKAGE=idyll-document

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script: cd packages/$PACKAGE && npm test
